### ISSUE TITLE
Skype Bot not working Delivery Failed

### ISSUE THREAD

**Issue by murtazadhari** [Microsoft/BotBuilder#1309]
Hi, 

My bot is not working on skype. When i send message it comes back with warning sign on message "delivery failed"
The same bot works on emulator and sms. It was working last week but it has suddenly stopped.

Cheer
Ali, Murtaza

**Comment by murtazadhari** [comment]
Hi @willportnoy 

Any updates on this? I have noticed not only my bot all the other live bots are not working. Same issue is happening with other live bots. Messages coming back with delivery failed warning icon.

**Comment by dandriscoll** [comment]
Hi @murtazadhari, all of the Skype bots I've tried are working properly.

Can you send an example bot ID (either the ID in the Bot Framework portal, or the GUID in the join bot link)?

**Comment by pcostantini** [comment]
Hi!
Same issue here and not just my bot. I'm getting 'delivery failed' while sending messages to any of the published bots in the directory (https://bots.botframework.com/).
I'm using the same skype account on different connections and clients (skype preview, skype desktop, skype alpha for linux and android client).

**Comment by murtazadhari** [comment]
Hi @dandriscoll 

This is the App Id 147820f6-870e-4308-8c6c-7c8ed2e70da6 of my bot.  It is not published yet. I am not sure whether you can still use it.

The other live bots that i have tried and all of these are coming back with same above error
Candy Escape
MemeBot
Skyscanner

**Comment by dandriscoll** [comment]
Hi @murtazadhari and @pcostantini, we are looking into it.

**Comment by konstlut** [comment]
@murtazadhari @pcostantini I will kindly ask you to help me troubleshoot that - will you please  try sending message to your Bot from Skype web app (web.skype.com) and see what actual HTTP request/response is when you send messages to Bot? Most interesting for me are response code and response headers ContextId and Date. 
If you use Microsoft Edge you may check the network tab in the Console (F12) as on the attached screenshot.
![image](https://cloud.githubusercontent.com/assets/20228162/18875933/08e1c156-84c8-11e6-9ae2-88d5b4cbeff3.png)

**Comment by pcostantini** [comment]
Hi @konstlut 
These are the response body and headers:

**Headers:**
Access-Control-Allow-Credentials: false
Access-Control-Allow-Origin: *
Access-Control-Expose-Headers: X-Content-Type-Options,Location,Cache-Control,Pragma,ContextId
Cache-Control: no-store, must-revalidate, no-cache
Content-Length: 37
Content-Type: application/json; charset=utf-8
ContextId: tcid=147498413417571991,server=CO2SCH020011051
Date: Tue, 27 Sep 2016 13:48:56 GMT
Location: https://co4-client-s.gateway.messenger.live.com/v1/users/ME/conversations/8:live:botbuilderpc/messages/1474984137196
Pragma: no-cache
X-Content-Type-Options: nosniff

**Body:**
{"OriginalArrivalTime":1474984137206}

![image](https://cloud.githubusercontent.com/assets/57197/18876461/32e64404-84a0-11e6-95e8-aa630b73e4f9.png)

**Comment by konstlut** [comment]
@pcostantini Thanks a lot! This is exactly what I need for investigation. We're treating this as a priority and I will update you as soon as possible - apologies for the delay in getting a resolution.

**Comment by murtazadhari** [comment]
Hi Konslut, Below is my detail

**Request Url**
Request URL: https://client-s.gateway.messenger.live.com/v1/users/ME/conversations/28:147820f6-870e-4308-8c6c-7c8ed2e70da6/messages

**Request Header**

   Accept: application/json, text/javascript
   Accept-Encoding: gzip, deflate
   Accept-Language: en-US, en-AU; q=0.7, en; q=0.3
   BehaviorOverride: redirectAs404
   Cache-Control: no-cache, no-store, must-revalidate
   ClientInfo: os=Windows; osVer=10; proc=Win32; lcid=en-us; deviceType=1; country=n/a;   clientName=skype.com; clientVer=908/1.60.0.72//skype.com
   Connection: Keep-Alive
   Content-Length: 152
   Content-Type: application/json
   ContextId: tcid=147502748556415801
   Expires: 0
   Host: client-s.gateway.messenger.live.com
   Origin: https://web.skype.com
   Pragma: no-cache
   Referer: https://web.skype.com/en/
   RegistrationToken: registrationToken=U2lnbmF0dXJlOjI6Mjg6QVFRQUFBQmwxUHYwTkdZQnkrZ1ppVk9PbE1OSDtWZXJzaW9uOjY6MToxO0lzc3VlVGltZTo0OjE5OjUyNDc3OTIyNjA2MDE5Nzk2MTU7RXAuSWRUeXBlOjc6MToxO0VwLklkOjI6MjQ6bXVydGF6YWRoYXJpQGhvdG1haWwuY29tO0VwLkVwaWQ6NTozNjpjNzQxMDMxOS05NTBlLTRlODEtOGViMi03OWRiMjdiMWJhM2E7RXAuTG9naW5UaW1lOjc6MTowO0VwLkF1dGhUaW1lOjQ6MTk6NTI0Nzc5MjI2MDYwMTA0MjA1NDtFcC5BdXRoVHlwZTo3OjI6MTU7RXAuRXhwVGltZTo0OjE4OjYzNjEwNzEwNjA4MDAwMDAwMDtVc3IuTmV0TWFzazoxMToxOjM7VXNyLlhmckNudDo2OjE6MDtVc3IuUmRyY3RGbGc6MjowOjtVc3IuRXhwSWQ6OToxOjA7VXNyLkV4cElkTGFzdExvZzo0OjE6MDtVc2VyLkF0aEN0eHQ6MjoyNzI6Q2xOcmVYQmxWRzlyWlc0WWJYVnlkR0Y2WVdSb1lYSnBRR2h2ZEcxaGFXd3VZMjl0QVFOVmFXTVVNUzh4THpBd01ERWdNVEk2TURBNk1EQWdRVTBNVG05MFUzQmxZMmxtYVdWa2VBdlp1Q3lQbi9ZQUFBQUFBQUJBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBRFcxMWNuUmhlbUV1WkdoaGNta0FBQUFBQUFBQUFBQUhUbTlUWTI5eVpRQUFBQUFFQUFBQUFBQUFBQUFBQUFCNEM5bTRMSStmOWdBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQVExdGRYSjBZWHBoTG1Sb1lYSnBBQUFBQUFBQUFBQUE7
   User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/42.0.2311.135 Safari/537.36 Edge/12.10240

**Request Body**
{"content":"hello","messagetype":"RichText","contenttype":"text","Has-Mentions":"false","imdisplayname":"Murtaza Ali","clientmessageid":"1475027485560"}


**Response Header**

   Access-Control-Allow-Credentials: false
   Access-Control-Allow-Origin: *
   Access-Control-Expose-Headers: Cache-Control,Pragma,ContextId
   Cache-Control: no-store, must-revalidate, no-cache
   Content-Length: 80
   Content-Type: application/json; charset=utf-8
   ContextId: tcid=147502748556415801,server=CO2SCH020011022
   Date: Wed, 28 Sep 2016 01:51:26 GMT
   Pragma: no-cache

**Response Body**
{"errorCode":205,"message":"One or more of the user ids provided is not valid."}

![skype bot](https://cloud.githubusercontent.com/assets/3989905/18898099/c76576e0-8572-11e6-96e3-51a0f79b6e50.png)

**Comment by kirankcinfy** [comment]
I'm facing the same issue as well. Please help.

**Comment by lucasmdesousa** [comment]
Same problem here

**Comment by twu7735** [comment]
I'm also facing the same issue
one thing I've noticed is that everything works fine if I switch to a diff account on the same computer
while msg delivery started failing at some point to every bot on my original account
my orig acct is skype/microsoft linked, if that helps anything

**Comment by marianojan** [comment]
Hello! A part of our team is having the same issue. We tried with a new account, not linked to Hotmail, and it seems to work. Sounds like the problem arises when the account is linked. In that case, none of the public bots works.
Is there something we can try to correct it?
Thanks!

**Comment by konstlut** [comment]
@pcostantini @murtazadhari Many thanks for the provided context! 

The problem should be resolved. Thank you for your patience.

**Comment by kirankcinfy** [comment]
Thank you @konstlut ... It works fine now

**Comment by marianojan** [comment]
Thank's a lot! It's working now.

**Comment by murtazadhari** [comment]
Hi @konstlut 

Other live bot works fine now but my bot is still not replying back but i am not getting delivery failed message back though?

My bot works on emulator.

Any Help?

**Comment by konstlut** [comment]
@murtazadhari Sure, I will need ContextId and Date headers you see on the client to check what is going on the way from Skype to Bot, and if you want to troubleshoot Bot's to Skype behavior, I will need same header values taken from responses your Bot sees. Thanks!

**Comment by murtazadhari** [comment]
Hi @konstlut 

Please see below details

**Request Header**

   Request URL: https://client-s.gateway.messenger.live.com/v1/users/ME/conversations/28:147820f6-870e-4308-8c6c-7c8ed2e70da6/messages
   Request Method: POST
   Status Code: 201 / Created


   Accept: application/json, text/javascript
   Accept-Encoding: gzip, deflate
   Accept-Language: en-AU
   BehaviorOverride: redirectAs404
   Cache-Control: no-cache, no-store, must-revalidate
   ClientInfo: os=Windows; osVer=10; proc=Win32; lcid=en-us; deviceType=1; country=n/a; clientName=skype.com; clientVer=908/1.61.0.68//skype.com
   Connection: Keep-Alive
   Content-Length: 152
   Content-Type: application/json
   ContextId: tcid=147546696357847373
   Expires: 0
   Host: client-s.gateway.messenger.live.com
   Origin: https://web.skype.com
   Pragma: no-cache
   Referer: https://web.skype.com/en/
   RegistrationToken: registrationToken=U2lnbmF0dXJlOjI6Mjg6QVFRQUFBQXRZVnpxQVFtRTB5cTBTK1RYcGJ6TztWZXJzaW9uOjY6MToxO0lzc3VlVGltZTo0OjE5OjUyNDc3OTY2NTU3ODczNDAzNDE7RXAuSWRUeXBlOjc6MToxO0VwLklkOjI6MjQ6bXVydGF6YWRoYXJpQGhvdG1haWwuY29tO0VwLkVwaWQ6NTozNjo5OTVjMGFkMy00ZWQ5LTQzOTMtYjc1NS04N2U1MmU3ZDRiMmQ7RXAuTG9naW5UaW1lOjc6MTowO0VwLkF1dGhUaW1lOjQ6MTk6NTI0Nzc5NjY1NTc4MzI3NzY4MztFcC5BdXRoVHlwZTo3OjI6MTU7RXAuRXhwVGltZTo0OjE4OjYzNjExMTUwMTIxMDAwMDAwMDtVc3IuTmV0TWFzazoxMToxOjM7VXNyLlhmckNudDo2OjE6MDtVc3IuUmRyY3RGbGc6MjowOjtVc3IuRXhwSWQ6OToxOjA7VXNyLkV4cElkTGFzdExvZzo0OjE6MDtVc2VyLkF0aEN0eHQ6MjoyNzI6Q2xOcmVYQmxWRzlyWlc0WWJYVnlkR0Y2WVdSb1lYSnBRR2h2ZEcxaGFXd3VZMjl0QVFOVmFXTVVNUzh4THpBd01ERWdNVEk2TURBNk1EQWdRVTBNVG05MFUzQmxZMmxtYVdWa2VBdlp1Q3lQbi9ZQUFBQUFBQUJBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBRFcxMWNuUmhlbUV1WkdoaGNta0FBQUFBQUFBQUFBQUhUbTlUWTI5eVpRQUFBQUFFQUFBQUFBQUFBQUFBQUFCNEM5bTRMSStmOWdBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQVExdGRYSjBZWHBoTG1Sb1lYSnBBQUFBQUFBQUFBQUE7
   User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2486.0 Safari/537.36 Edge/13.10586

**Request Body**
{"content":"hello","messagetype":"RichText","contenttype":"text","Has-Mentions":"false","imdisplayname":"Murtaza Ali","clientmessageid":"1475466963571"}


**Response Header**

   Access-Control-Allow-Credentials: false
   Access-Control-Allow-Origin: *
   Access-Control-Expose-Headers: X-Content-Type-Options,Location,Cache-Control,Pragma,ContextId
   Cache-Control: no-store, must-revalidate, no-cache
   Content-Length: 37
   Content-Type: application/json; charset=utf-8
   ContextId: tcid=147546696357847373,server=CO2SCH020011051
   Date: Mon, 03 Oct 2016 03:56:13 GMT
   Location: https://co4-client-s.gateway.messenger.live.com/v1/users/ME/conversations/28:147820f6-870e-4308-8c6c-7c8ed2e70da6/messages/1475466974356
   Pragma: no-cache
   X-Content-Type-Options: nosniff

**Response Body**
{"OriginalArrivalTime":1475466974352}

**Comment by murtazadhari** [comment]
Hi @konstlut 

Any updates regarding the above issue.

Cheers

**Comment by konstlut** [comment]
@murtazadhari It looks like your bot is getting the message but (just assumption) things break when it POSTs back. What is it sending?

**Comment by murtazadhari** [comment]
Hi @konstlut 

Suddenly skype is replying back. I will close this issue. However there is an issue with email validation on skype i will open an another issue for it after verifying it multiple times.

Thanks for all your help.

Cheers

**Comment by jmarellano** [comment]
Hi. I am having the same problem here "sending failed".  Here is my response headers: 
`Response Headers
view source
Access-Control-Allow-Credentials:false
Access-Control-Allow-Origin:*
Access-Control-Expose-Headers:StatusText,Cache-Control,Pragma,ContextId,Date
Cache-Control:no-store, must-revalidate, no-cache
Content-Length:80
Content-Type:application/json; charset=utf-8
ContextId:tcid=151559755434886034,server=EAP010097224114
Date:Wed, 10 Jan 2018 15:19:14 GMT
Pragma:no-cache
Server:Microsoft-HTTPAPI/2.0
StatusText:One or more of the user ids provided is not valid.`

**Comment by JasonSowers** [comment]
@jmarellano can you please open a new issue
