### ISSUE TITLE
Webchat issues on Safari (desktop + mobile)

### ISSUE THREAD

**Issue by digitallawyer** [Microsoft/BotBuilder#1708]
As a user, when interacting with my bot using Safari (on desktop or on iPhone),
the dialog does not progress beyond the initial interaction.

To reproduce:

[Talk to the bot](https://lara.legal.io/lara) on Chrome - everything works as intended.
[Talk to the bot on Safari](https://lara.legal.io/lara) - you will be unable to get past the initial dialog.

This may be related to [issue 1430](https://github.com/Microsoft/BotBuilder/issues/1430).

**Comment by dandriscoll** [comment]
Hi @digitallawyer, it looks like the embed is not assigning a user ID, which causes the flow to restart after every message. We've released a new embed and have moved the location of the user ID assignment. You can enable it by checking the "Web chat preview" box on the Web Chat configuration page within the Bot Framework developer portal.

We'll look at fixing this in the old control but over time we'll be upgrading to the new codebase so if the new control works for you, you may be able to upgrade now to avoid the wait.

**Comment by digitallawyer** [comment]
Upgraded and confirmed working. Thanks!

**Comment by mmentawe** [comment]
Hi @digitallawyer,   what did you upgrade? I am facing the same issue.

**Comment by dandriscoll** [comment]
Hi @mmentawe, open the Web Chat configuration panel on your bot's dashboard at dev.botframework.com and check the "Enable Preview" button

**Comment by mmentawe** [comment]
Hi @dandriscoll, it is already checked and still not working, so I looked at the source code of the preview webchat control on my bots page and noticed this features=webchatpreview in the webchat burl, used it and it works.

am I doing something wrong?

**Comment by digitallawyer** [comment]
I remember running into the same issue. If I remember correctly, a redeploy fixed it, but I am not 100% certain.
