### ISSUE TITLE
[Telegram] Proactive bot in C# would not work in Telegram

### ISSUE THREAD

**Issue by isaacy** [Microsoft/BotBuilder#1983]
Repro:
1. Create a proactive bot in c#.
2. Register the bot with Telegram.
3. in Telegram, add the bot, and send a message.

Expected:
The bot will be able to receive the queued message.

Actual
The bot was not able to recevied the queued message.
in the bot log, here is the error:

2017-01-07T06:42:01.536 Function completed (Failure, Id=e680d066-9132-4e63-89bd-61badd49fbe1)
2017-01-07T06:42:01.552 Exception while executing function: Functions.messages. Microsoft.Bot.Connector: Unknown bot .

This does not repro in proactive bot for JS though.

**Comment by eanders-MS** [comment]
@msft-shahins Any idea why this would fail for a bot developed in C#, but succeed with a Node.JS bot?

**Comment by jameslew** [comment]
@maxpert , any ideas?

**Comment by macrobug** [comment]
So far I have identified this is the line where the error occurs:

`await client.Conversations.ReplyToActivityAsync(triggerReply);`

That is inside:

`case ActivityTypes.Trigger:`

In the file `run.csx`

Seems like the ResumptionCookie is wrong or something along those lines.

**Comment by isaacy** [comment]
This is fixed now?

**Comment by eanders-MS** [comment]
We've tracked down the issue, and a fix is in progress. Thanks for your patience.

**Comment by macrobug** [comment]
Thanks @eanders-MS , Would you let us know when this fix is deployed to the portal?

**Comment by kkarahainko** [comment]
@eanders-MS any updates?

**Comment by SkyQuant** [comment]
Should I already start to write native Telegram bot or update with fixed proactive messaging problem is coming?

**Comment by eanders-MS** [comment]
Apologies for the slow response here. A fix for this issue is still planned, but at the moment I cannot provide a timeline for when it will be done.

**Comment by nwhitmont** [comment]
@isaacy Are you still experiencing the issue after upgrading to [BotBuilder 3.8.1](https://www.nuget.org/packages/Microsoft.Bot.Builder/)?

**Comment by nwhitmont** [comment]
@kkarahainko Are you still experiencing the issue after upgrading to [BotBuilder 3.8.1](https://www.nuget.org/packages/Microsoft.Bot.Builder/)?

**Comment by castillolj** [comment]
The issue persist in 3.8.1, anyone can help me to workaround?

**Comment by eanders-MS** [comment]
A user posted a workaround here: https://github.com/Microsoft/BotBuilder/issues/2347

> This error occurs if you only specify the Id "new ChannelAccount (botId)" If you add the name "new ChannelAccount (botId, botName)", everything will work

**Comment by supercoja** [comment]
I had the same issue with Telegram, using version 3.15.3.
The workaround with creating ChannelAccount(botId,BotName) instead of only ChannelAccount(botId) not worked. The error "The bot referenced by the 'from' field is unrecognized"
The issue/bug still exists?

**Comment by EricDahlvang** [comment]
@supercoja  Please open a new issue https://github.com/Microsoft/BotBuilder/issues/new
