### ISSUE TITLE
[NodeJS]: FB endpoint and '[503] Service Unavailable' errors

### ISSUE THREAD

**Issue by vorti2** [Microsoft/BotBuilder#2140]
Hi,

our NodeJS bot has worked, but in the last couple of hours if the bot wants to communicate with FB via MSBF we see error messages like 
```
2017-01-31T00:05:57.182232306Z Error: Request to 'https://facebook.botframework.com/v3/conversations/1223107254396606-1870799656480238/activities/mid.1485820818592%3A4e2ec87315' failed: [503] Service Unavailable
2017-01-31T00:05:57.182273084Z     at Request._callback (/app/node_modules/botbuilder/lib/bots/ChatConnector.js:434:46)
2017-01-31T00:05:57.182278679Z     at Request.self.callback (/app/node_modules/request/request.js:186:22)
2017-01-31T00:05:57.182282394Z     at emitTwo (events.js:106:13)
2017-01-31T00:05:57.182285668Z     at Request.emit (events.js:191:7)
2017-01-31T00:05:57.182288987Z     at Request.<anonymous> (/app/node_modules/request/request.js:1081:10)
2017-01-31T00:05:57.182292922Z     at emitOne (events.js:96:13)
2017-01-31T00:05:57.182296022Z     at Request.emit (events.js:188:7)
2017-01-31T00:05:57.182299061Z     at IncomingMessage.<anonymous> (/app/node_modules/request/request.js:1001:12)
2017-01-31T00:05:57.182302408Z     at Object.onceWrapper (events.js:290:19)
2017-01-31T00:05:57.182305394Z     at emitNone (events.js:91:20)
2017-01-31T00:05:57.182308319Z     at IncomingMessage.emit (events.js:185:7)
2017-01-31T00:05:57.182311596Z     at endReadableNT (_stream_readable.js:974:12)
2017-01-31T00:05:57.182314566Z     at _combinedTickCallback (internal/process/next_tick.js:74:11)
2017-01-31T00:05:57.182317581Z     at process._tickDomainCallback (internal/process/next_tick.js:122:9)
2017-01-31T00:05:57.182320861Z
``` 
For our implementation we use
```
    "botbuilder": "^3.5.4",
```

Any idea?

Thanks,
Wilhelm

**Comment by teddis** [comment]
👍 This is happening to me too right now. Great timing, we have a huge, important demo tomorrow for potential partnership and funding.

**Comment by eanders-MS** [comment]
Bot Framework ops is aware of the issue and is actively investigating.

**Comment by alonsonic** [comment]
@eanders-MS do we have a confirmation that this issue was solved?

I was experiencing the same problems yesterday, but tested the chatbots now and they are performing well.

**Comment by vorti2** [comment]
We have the following information from chatbot group on FB:
```
Lucas Ives commented on your post in Bots.
MS had a huge service outage this morning where their authentication mechanism was down. Lots of folks were bitten.
```

Okay, when the problem is solved for now, what do we have learned for the future?

**Comment by teddis** [comment]
We all depend on 3rd party services, but the bot framework is still in preview. This is not the first outage in the last few months and its added delay is still unfortunate. I don't mean to complain, but it still doesn't give me that warm and fuzzy of something we can rely on for mission critical bots, esp. ones that generate revenue. It's great for a playground. It's wonderfully novel middleware, but isn't ready for prime time yet. There's no direct way to contact support or ops and no stated QoS. What do you expect for free? Curious how many are relying on this for production bots.

**Comment by vorti2** [comment]
Yes, the small hint "Preview" on the home page ... Would be interesting to know a little bit more about MS plans (and time schedule) for the bot framework.
