### ISSUE TITLE
[Skype For Business, Node.js SDK, Question] Bot status is "Unknown" on Skype for Business

### ISSUE THREAD

**Issue by panosVeran** [Microsoft/BotBuilder#3017]
## System Information (Required)
* SDK Language: node js

## Issue Description
i have a bot and deployed it in regular skype fine, everything works perfectly, i want to make it work in skype for business, i downloaded the connector module and run the commands described in your documentation etc etc. the bot works OK but i have some problems. 

1. bot's status is unknown, how to make it available as i would expect?

2. bot's image doesn't appear.

**Comment by Mikhail2k15** [comment]
AFAIK 1 & 2 are known issues during developer preview.

**Comment by PerBendixen** [comment]
Is Microsoft aware that this i a problem ?

**Comment by andysia365** [comment]
I have the same issue - hopefully a fix soon?

**Comment by intranetchris** [comment]
We also have the first issue — bot status is "unknown". Any update on this?

**Comment by sinhautkarsh2014** [comment]
This issue has been with our sfb bot for a while now too. Please come up with a fix soon?

**Comment by Shamrh** [comment]
I am also facing the same issue 
![image](https://user-images.githubusercontent.com/32353229/33612140-ad7304b2-d9f6-11e7-8a24-077ac39c4027.png)

**Comment by satyansh-sagar** [comment]
How long will it take to resolve the issue, I'm facing the issue since a long time now and now the Framework is in General Availability, i think it should be resolved.
any updates @msmohan @nwhitmont @msft-shahins @msftdata

**Comment by EricDahlvang** [comment]
from the Skype for Business team:

> 
> 1. bot's status is unknown
> 2. bot's image doesn't appear.
> 
> Both features are not available currently with Skype for Business bots. 
> 
> Skype for Business Bots are still in Developer Preview. There is no timeline for these features.

**Comment by gowthamsanj** [comment]
Hi

Bot status is 'Presence unknown' due to this I can transfer the file to Skype for business, May I know when will this issue get resolved?

Thanks

**Comment by mrgorzny** [comment]
Any news about this yet? We're experiencing the same problem. It's not vital but it's frustrating because there are some articles clearly showing screenshots from Skype for business where both user thumbnail and user status are clearly shown. (E.g. https://chatbotsmagazine.com/enterprise-chatbots-on-skype-for-business-af635f346f5c)

**Comment by sinhautkarsh2014** [comment]
After assigning an Exchange Online license to the bot, the bot image would appear. Bot status still can't be set.

**Comment by amitgaikwad18** [comment]
Is there any update on this?

**Comment by srae23** [comment]
Any news on this item yet?

**Comment by satyansh-sagar** [comment]
This is still in preview, will out out as it moves to GA.

On 5 Mar 2018 16:10, srae23 <notifications@github.com> wrote:

Any news on this item yet?

**Comment by dkonyayev** [comment]
This issue is putting out our production deploy of MS Bot application. Users will not start a conversation with bot if it doesn't appear online. I initially thought it was a minor config issue and put off looking at it. But now that we are ready to launch I realize that this bug means a NoGo for us.

**Comment by furkankatman** [comment]
Any good news about this issue ?

**Comment by tinakashyap** [comment]
Bot status  is showing as "Presence Unknown". Has Microsoft come up with any fix? Or can anybody help?

The bot image issue has been fixed after assigning an Exchange Online license to the bot.

**Comment by robertovalenzuela91** [comment]
Hi Is there any update on this?  "Presence unknown"

![image](https://user-images.githubusercontent.com/2516883/45389144-bc39b380-b5e0-11e8-91fa-5e27a0b5820c.png)

**Comment by carlosscastro** [comment]
Thank you for opening an issue against the Bot Framework SDK v3. As part of the Bot Framework v4 release, we’ve moved all v3 work to a new repo located at https://github.com/microsoft/botbuilder-v3. We will continue to support and offer maintenance updates to v3 via this new repo.
 
From now on, https://github.com/microsoft/botbuilder repo will be used as hub, with pointers to all the different SDK languages, tools and samples repos.
 
As part of this restructuring, we are closing all tickets in this repo.
 
For defects or feature requests, please create a new issue in the new Bot Framework v3 repo found here:
https://github.com/microsoft/botbuilder-v3/issues

For Azure Bot Service Channel specific defects or feature requests (e.g. Facebook, Twilio, Teams, Slack, etc.), please create a new issue in the new Bot Framework Channel repo found here:
https://github.com/microsoft/botframework-services/issues
 
For product behavior, how-to, or general understanding questions, please use Stackoverflow.
https://stackoverflow.com/search?q=bot+framework


Thank you.
 
The Bot Framework Team
