### ISSUE TITLE
[Bug] Suggested Actions not working in Skype

### ISSUE THREAD

**Issue by auanish** [Microsoft/BotBuilder#3076]
## System Information (Required)
•SDK Language: Node
•SDK Version: BotFramework 3.8.3
•Development Environment: AZURE_APP_SERVICE
 

## Issue Description
I'm unable to see suggested actions in my Skype bot. I can see them in my emulator and even webchat but not in Skype. 

Under the Skype Health section in the dashboard, it says "Unknown activity type"

## Code Example
Just reusing the code from [here](https://docs.microsoft.com/en-us/bot-framework/nodejs/bot-builder-nodejs-send-suggested-actions)

**Comment by xjose97x** [comment]
I believe that is a known issue. I read before that SuggestedActions are not supported. 
Not sure what's the current status of this issue.

**Comment by auanish** [comment]
If you look at the [Skype developers website](https://dev.skype.com/bots), it says Suggested Actions are supported.

![2017-07-03 18_27_42-skype for developers](https://user-images.githubusercontent.com/24720506/27802730-836ad1fc-601d-11e7-926e-a6a1ab6f403e.png)

**Comment by nwhitmont** [comment]
Can confirm, suggested actions are not working on Skype channel. Reproduced via this example: https://github.com/Microsoft/BotBuilder/blob/master/Node/examples/feature-suggestedActions/app.js

**Comment by nwhitmont** [comment]
@Stevenic

**Comment by Magic73** [comment]
Suggested actions are supported only in the lastest version of the Android's app.
Windows Store version doesn't show the buttons, instead if I use my S8+ I can use them.

**Comment by khs3141** [comment]
It does not work with SKYPE latest Android's app downloaded from play store.

SKYPE : VERSION 8.2.0.49163
SKYPE PREVIEW : VERSION 8.3.76.50301

**Comment by Magic73** [comment]
It works. I have a S8+ with Skype 8.2.0.49163.
you are doing something wrong...

**Comment by khs3141** [comment]
Through remote debugging, found the cause of the error.
ex.Message : "Activity must include non empty 'text' field or at least 1 attachment"

In emulator and webchat, this exception did not occur, but occured in skype.
After setting the value of message.text, it is normally expressed.

Thank you for your help.

**Comment by auanish** [comment]
@khs3141 can you please elaborate what you mean by setting the value of message.text? What piece of code should I add to this [example ](https://github.com/Microsoft/BotBuilder/blob/master/Node/examples/feature-suggestedActions/app.js)to make Suggested Actions work in Skype?

**Comment by Magic73** [comment]
`var reply = activity.CreateReply();
reply.Type = ActivityTypes.Message;
reply.Text = ""; // This cannot be null, or skype won't work.
reply.TextFormat = TextFormatTypes.Plain;

reply.SuggestedActions = new SuggestedActions()
{
	Actions = new List<CardAction>()
	{
		new CardAction(){ Title = "Blue", Type=ActionTypes.ImBack, Value="Blue" },
		new CardAction(){ Title = "Red", Type=ActionTypes.ImBack, Value="Red" },
		new CardAction(){ Title = "Green", Type=ActionTypes.ImBack, Value="Green" },
	   
	}
};
await context.PostAsync(reply);`

**Comment by Magic73** [comment]
BTW, you can have suggested actions on the skype windows store version... but with a bug also:

on my previous code, just before PostAsync(reply), add this:

```
reply.Attachments = new List<Attachment>
    {
        new KeyboardCard(text: "Options:", buttons: reply.SuggestedActions.Actions).ToAttachment()
     };
```

and like a magic... you'll see the suggested actions buttons! but... you'll see the keyboardcard also :)

so, there's something that has been forget in the suggestedactions implementations for skype, that is present when keyboardcard is used.

**Comment by sangmai** [comment]
I'm facing similar issuer. My suggestion is only shown in mobile (IOS, android, Emulator)

**Comment by antpant89** [comment]
@Magic73 - This is fucked up. You are correct. Wonder if the Skype team will fix this...

**Comment by Daddymarto01** [comment]
The issue has been fixed in the latest versions of skype. I've tried on Skype for desktop and failed, but the SuggestionActions are showing on both skype android app and skype for windows 10

**Comment by Kaijiro** [comment]
It is not working for me, on any devices tested (Skype for Android (v8.25.0.5), Skype for Ubuntu (v8.13.0.2) and even Skype Web).

Any informations about this issue ?

**Comment by Daddymarto01** [comment]
@Kaijiro try Skype for Windows 10 PC. They should work... Also on Android 6.0 that am using the suggested actions are ok. If still can not show then please share code.

**Comment by Kaijiro** [comment]
Tried on W10 with client version 12.1815.209.0 : still not working.

**Comment by Daddymarto01** [comment]
Kindly share code I see if I can assist

**Comment by benbrown** [comment]
Thank you for opening an issue against the Bot Framework SDK v3. As part of the Bot Framework v4 release, we’ve moved all v3 work to a new repo located at https://github.com/microsoft/botbuilder-v3. We will continue to support and offer maintenance updates to v3 via this new repo.
 
From now on, https://github.com/microsoft/botbuilder repo will be used as hub, with pointers to all the different SDK languages, tools and samples repos.
 
As part of this restructuring, we are closing all tickets in this repo.
 
For defects or feature requests, please create a new issue in the new Bot Framework v3 repo found here:
https://github.com/microsoft/botbuilder-v3/issues

For Azure Bot Service Channel specific defects or feature requests (e.g. Facebook, Twilio, Teams, Slack, etc.), please create a new issue in the new Bot Framework Channel repo found here:
https://github.com/microsoft/botbuilder-channels/issues
 
For product behavior, how-to, or general understanding questions, please use Stackoverflow.
https://stackoverflow.com/search?q=bot+framework


Thank you.
 
The Bot Framework Team
