### ISSUE TITLE
Skype Bot: No event received when sending image file to bot

### ISSUE THREAD

**Issue by bostondv** [Microsoft/BotBuilder#347]
Botbuilder: 0.11.1
Skype for windows: 7.24.0.104
Skype SDK: node.js 1.0.6

Using new `builder.Prompts.attachment()` or just simply sending an image file to bot with a basic dialog listening at `/` no event is received by the bot. 

Example:

```
bot.add('/', [
  (session) => {
    builder.Prompts.attachment(session, 'Please give me a file...');
  },
  (session, results, next) => {
    if (results.response) {
      console.log('File received.');
    } else {
      console.log('No file received.');
    }
  }
]);
```

I'd expect the 2nd step in the waterfall to be trigged by sending an image to the bot via the Skype client, however it never does. Replying to the prompt with text triggers the next step fine as the bot replies with `I didn't receive a file. Please try again.`.

Additionally, on Windows Skype client I can only send image files (Send File icon is disabled and not sure why). On OS X there is no capability as of v7.28 (316) to send any file or image to a bot. However on OSX v7.26 sending a one was possible, it had the same problem with images but a file (such as a PDF) did trigger an event on the bot server side.

**Comment by Stevenic** [comment]
I don't believe skype supports image upload yet... Let me ask internally

**Comment by bostondv** [comment]
Thanks! 

Just to clarify, here's what I'm seeing on the various Skype clients:

OS X: No image or file upload

![screen shot 2016-05-27 at 3 12 06 pm](https://cloud.githubusercontent.com/assets/133814/15618757/d8c18f16-241d-11e6-9ab7-463436b2292f.png)

Windows: Image upload available but file upload disabled

![screen shot 2016-05-27 at 3 13 07 pm](https://cloud.githubusercontent.com/assets/133814/15618775/ed24c450-241d-11e6-977d-ffcaa90f0a17.png)

Web: Image / File upload button is combined and available but Bot has an error accepting files from Web client.

![screen shot 2016-05-27 at 3 12 53 pm](https://cloud.githubusercontent.com/assets/133814/15618795/00449c68-241e-11e6-85b9-bf10789f37e6.png)

**Comment by Stevenic** [comment]
So from another bug there was apparently a bug on our side. They supposedly deployed a fix yesterday, You might try again.

**Comment by Stevenic** [comment]
can you please reopen if you're having issues with this. we deployed a fix,

**Comment by bostondv** [comment]
I don't believe I have access to re-open the ticket, but just upgraded to BotBuilder 1.0.1 and tested. Image files still are not triggering the 2nd step in both Windows and OS X.

The OS X Skype client attachment button however is now available, so that's good! On Windows, the file attachment is still not available.

Additionally, now that OS X attach button works I've found that when attaching non-images, like a PDF, the `attachment` prompt is returning a `I didn't receive a file. Please try again.` message rather than triggering the 2nd step of waterfall with attachment data. Would you suggest I open a separate ticket for this?

**Comment by Stevenic** [comment]
Ok... That sounds like a client issue. There's not much we're going to be able to do about that.

**Comment by v-thgratMSGit** [comment]
Closing this issue. Please open a new issue for further discussion if necessary. Thanks!
