### ISSUE TITLE
Bad error messages when using OAUTH in bot with invalid AppId / Secret

### ISSUE THREAD

**Issue by devedse** [Microsoft/BotBuilder#4642]
## Bot Info
* SDK Platform: .NET
* SDK Version: 3.15.2.2
* Active Channels: Bot Emulator
* Deployment Environment: Azure Bot Service with Azure Functions + local development with Emulator?

## Issue Description
I deployed a bot to Azure with some specific AppId and Secret. I then created a local bot with a different AppId and Secret so they wouldn't conflict.

I ran the bot locally and everything worked fine. However when I started to implement authentication using this tutorial: https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-tutorial-authentication?view=azure-bot-service-3.0 I ran into  some issues.

Whenever I tried to connect to the bot it would start the OAUTH procedure but when Clicking on the SignIn button an error appeared that the URL must be a string, not undefined.

![image](https://user-images.githubusercontent.com/2350015/40358657-45558c6c-5dc0-11e8-8a18-d030624ae905.png)

## Reproduction Steps
1. Create bot in Azure with AppId and Secret
2. Create bot locally and run in Emulator with different AppId and Secret
3. Implement authentication in Local bot
4. Talk to local bot using bot emulator
5. When the SignIn card appears, click on the "Sign in" button

## Expected Behavior
I expect a message or exception like this:
"Error when trying to start OAUTH procedure. Connection to Azure Bot Service with AppId failed because the AppId's don't match"

## Actual Results
The error message:

> Parameter "url" must be a string, not undefined

**Comment by JasonSowers** [comment]
Thank you for pointing this out, I have made the team aware of your request.

**Comment by KayMKM** [comment]
I met a same issue. Did you have a fix now?

**Comment by rbohanno** [comment]
Is there any progress on this? I also receive the same _"Parameter "url" must be a string, not undefined"_ while trying to test the oauth sign in card through the emulator. I followed the guidelines specified here: https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-tutorial-authentication?view=azure-bot-service-3.0

**Comment by devedse** [comment]
What we also noticed is that the Sign In card doesn't work in the emulator. So just use Skype Text or something.

**Comment by JasonSowers** [comment]
Apologies, I marked this as a feature request and it fell off my radar, not exactly sure what happened there.

 I spent the last couple days working through and debugging the Auth walkthrough you mention.  What issues are you seeing?  I am able to render and use the sign in card just fine in the emulator.  Are you still experiencing any issues?  

There was a bug that required you to sign in every time you entered a command that is fixed now, there is also a bug in webchat where the signin card link will not open correctly.

**Comment by JasonSowers** [comment]
Going to close this issue please open a new one if you need any assistance.

**Comment by krishnr** [comment]
This issue still exists in the Node SDK. If the emulator connects to an Azure-deployed bot with the wrong AppID or Secret then the SignIn card button gives the following error:

`Parameter "url" must be a string, not undefined`

This error is vague and unhelpful.
