### ISSUE TITLE
Is it possible to receive an image when working with LUIS (i.e. IntentDialog)?

### ISSUE THREAD

**Issue by htaunay** [Microsoft/BotBuilder#821]
I'm currently using LUIS to treat my input, using this straight-forward approach, as seen in the documentation:

``` javascript
var model = process.env.LUIS_URL;                                               
var recognizer = new builder.LuisRecognizer(model);                             
var dialog = new builder.IntentDialog({ recognizers: [recognizer] });
var bot = new builder.UniversalBot(connector);                                                                     
bot.dialog('/', dialog ); 
```

However, when I'm sending the bot images, I can't seem to find any attachments. I'm guessing maybe LUIS ignores image input? If so, is there a way to overcome this issue?

Thanks in advance!

**Comment by htaunay** [comment]
Update:
If I don't set the LUIS dialog as the default endpoint, and use the `builder.Prompts.attachment` method, I can successfully retrieve a user-sent image.

What I'm after specifically is a way to work with both dialogs in parallel. Something in the lines of the following logic:

- if LUIS intent is 'X', then prompt for image
- else keep using LUIS intent default dialog

**Comment by htaunay** [comment]
Ok, I think I solved it... kind of...

The `dialog.matches` method from the `IntentDialog` seems to also work with **waterfall**, and therefore I am able to call the `builder.Prompts.attachment` from inside it and obtain the user sent input in the next step.

However, I will - apparently - always be stuck within the workflow: a LUIS intent is triggered, **then** I call the `builder.Prompts.attachment` method. The approach suggested in my previous message: to be able to test if an attachment if present **before** triggering LUIS (or any other dialog alternative) is still unclear to me.

**Comment by Andrea-Orimoto** [comment]
@htaunay have you been able to get clarity on this, or do you still need help?

**Comment by htaunay** [comment]
Hi @Andrea-Orimoto, thanks for the reply

I actually haven't managed to achieve what I was after originally, which was to be able to deal with a received image files within the LUIS dialog, i.e. when using an `IntentDialog` - with `LuisRecognizer`-  as my default dialog object I still can't manage to receive image files.

The solution I posted in my last comment involves using a specific intent as a trigger to then call `builder.Prompts.attachment`, and only then I can receive an image. But this approach will never work with a very basic use case: when a user sends an image without sending any text before.

Maybe I'm doing something wrong that you can point out?

**Comment by willportnoy** [comment]
@Stevenic can you invoke an attachment prompt preferentially before dispatching to LUIS?

**Comment by Stevenic** [comment]
Sorry for the delay... I published a fix a week or two ago which will let you create a new recognizer that looks for uploaded files and maps that to an intent. Basically you can create a recognizer that anytime it sees an attachment triggers an intent like "ImageUploaded" which you can then handle with a matches() clause.

**Comment by briangardner** [comment]
@Stevenic Do you have some sample code on how to create a recognizer that sees an attachment?  I'm trying to do this, and can't quite figure it out.

**Comment by willportnoy** [comment]
@briangardner there might be some relevant sample code in https://github.com/Microsoft/BotBuilder-Samples but I'm not sure.

**Comment by fms-santos** [comment]
I had the same problem dealing with LUIS and image attachments... What I did was using the ondefault() method for looking first for attachments and only after that send the "default message". Works really well in my example.

**Comment by briangardner** [comment]
Try the following.  It works for me.  Might still have issues on Skype, MS Teams, and the other channels that require you to get a JWT before getting the image.

    const customRecognizers = {
        AttachmentRecognizer: function(intent) {
            this.recognize = function(context, callback) {
                var score = 0;
    
                if (context.message.attachments && context.message.attachments.length > 0) {
                    score = 1;
                }
    
                callback(null, {
                    intent: intent,
                    score: score,
                    context: context
                });
    
            };
        }
    
    };
    
    module.exports = customRecognizers;

**Comment by fms-santos** [comment]
In my case, my solution works fine (even with Skype) for attachments, my problem actually is dealing with Hero Cards button actions and LUIS. 
I'm using a _builder.CardAction.postBack()_ and I want to trigger a certain function when a user taps "YES" or "NO".
