### ISSUE TITLE
[Facebook Messenger] Newlines stripped out when sending messages

### ISSUE THREAD

**Issue by MironV** [Microsoft/BotBuilder#920]
Sending messages seems to strip out multiple newlines (to create whitespace). Newlines are supported on FB Messenger but when I route them through Bot Framework they seem to disappear.

**Comment by Stevenic** [comment]
I've seen this too. Adding Tom.

**Comment by letmaik** [comment]
Any news? I've just hit that. It works in the emulator but on skype the newlines are missing. I use two whitespaces and then a `\n`.

**Comment by msft-shahins** [comment]
Since by default everything parsed as markdown you can put `\n\n` to have new paragraph in Skype and Facebook: 

```
"Lorem ipsum dolor sit amet, \n\n consectetur adipiscing elit. \n\n Duis eleifend efficitur orci, id semper leo feugiat at. Morbi pharetra massa sit amet nisi semper, sed pellentesque tellus egestas. \n\n Praesent ipsum enim, mollis ac imperdiet in, faucibus ut odio. Proin ut dui nisi."
```

Facebook: 
![image](https://cloud.githubusercontent.com/assets/17562300/18150505/2c3c86cc-6f9c-11e6-9a71-52a114cc7555.png)

Skype:
![image](https://cloud.githubusercontent.com/assets/17562300/18150508/3bc125c6-6f9c-11e6-8c0f-8b5d3defcfed.png)

Slack: 
![image](https://cloud.githubusercontent.com/assets/17562300/18150540/8069aebe-6f9c-11e6-9368-b40bc5a556be.png)

**Comment by MironV** [comment]
That seems to produce indented paragraphs. Is there a way to produce block paragraphs (i.e., create blank lines)? A lot of my content is really hard to read otherwise.

**Comment by acparas** [comment]
@MironV 

I have the same question. @msft-shahins closed my [issue](https://github.com/Microsoft/BotBuilder/issues/1112), which detailed this exactly.

**Comment by msft-shahins** [comment]
@MironV this should be fixed now. Use standard markdown `  \n` (two whitespace and `\n`) to insert a line break. 

```csharp
Text = "Lorem ipsum dolor sit amet,  \nConsectetur adipiscing elit.  \nDuis eleifend efficitur orci, id semper leo feugiat at. Morbi pharetra massa sit amet nisi semper, sed pellentesque tellus egestas.  \nPraesent ipsum enim, mollis ac imperdiet in, faucibus ut odio. Proin ut dui nisi."
```

Facebook
![image](https://cloud.githubusercontent.com/assets/17562300/18219516/ff2fff04-711e-11e6-8cfb-dd94859438c0.png)


Skype
![image](https://cloud.githubusercontent.com/assets/17562300/18219523/0ba5563a-711f-11e6-8e71-5a5df2df546f.png)

Webchat
![image](https://cloud.githubusercontent.com/assets/17562300/18219543/424ba43c-711f-11e6-95f3-4720171eb142.png)

**Comment by letmaik** [comment]
Are you sure this is completely solved? We are now seeing an additional blank newline at the end of most messages (tested via skype). I haven't tested the on-purpose newlines yet.

**Comment by msft-shahins** [comment]
@letmaik Feel free to file another issue with the markdown causing the behavior that you are observing.

**Comment by MironV** [comment]
@letmaik that sounds like issue #1025 which I filed some time ago. Looks like it hasn't been fixed yet.

**Comment by euanlau** [comment]
I am still not able to create blank lines. Is this really fixed?

@msft-shahins  your example does not contain blank lines.

**Comment by gilesbutler** [comment]
I can create a new line but can't seem to create a line between them... 
```
Hey,  \n  \nI\'m TestBot

Hey,
I’m TestBot
``` 

Any ideas how to get an extra blank line?

**Comment by euanlau** [comment]
@gilesbutler try ```line 1<br/><br/>line 3```

**Comment by gilesbutler** [comment]
Thanks @euanlau - unfortunately due to a family bereavement I can't test this right now. Once I'm back online I'll test and update here.

**Comment by McGern** [comment]
Hi, I am also trying to get lines between sentences to break up longer paragraphs

**Comment by maba4891** [comment]
Same issue here, after a lot of trial and error the only way to create blank lines (in the emulator) I have found is the following one:

```
var text1 = `Line1

&nbsp;
&nbsp;
  
Line3`;
```

which gives you:
Line1

Line3

But don't ask me why ;)

**Comment by nwhitmont** [comment]
@MironV if you're still experiencing this issue, can you provide additional detail so we can better assist you?

## Environment

* Operating System: 
  * Windows
  * macOS
  * Linux
* SDK Platform:
  * C#/.NET
  * Node.js
* SDK version:
* Development environment:
  * localhost
  * Azure Web App
  * Azure Bot Service App
  * other
* If you are using the Node.js SDK:
  * Node.js version:
  * NPM version: 

## Issue

What the issue is, in broad strokes. Link to [Stack Overflow](http://stackoverflow.com/search?q=%23botframework) post.

## Example Code

The code snippet or complete bot example (preferred) that demonstrates the issue.

## Steps to Reproduce

Please provide the shortest amount of steps to reproduce your issue.

## Expected Behavior

What you expected to happen.

## Actual Results

What actually happened. Please give examples and support it with screenshots, copied output or error messages.

**Comment by MironV** [comment]
I'm not sure I understand. It's pretty clear what the issue is and that people are continuing to encounter it. What more is specifically required that can't be parsed from this thread?

**Comment by nwhitmont** [comment]
@MironV are you using C# or Node SDK?

**Comment by maba4891** [comment]
Not sure what @MironV uses but I'm seeing this error in Node SDK

**Comment by hofman-p** [comment]
I have the same issue, I can't have a new line in Facebook channel. I tried all solutions I saw on this thread and in other places (<br>, <br />, ` nbsp; `,  \n  \n, \r\n, \r  \n...)
Is there a solution available and approved ?

**Comment by hofman-p** [comment]
Here is a new element I found:

![](https://puu.sh/wrdTi/c8ed14d63e.png)

Leads to this:

![](https://puu.sh/wrdV5/3719ccf115.png)

And if I take out the letters:

![](https://puu.sh/wrdXE/f75f2713c1.png)

It then leads to this:

![](https://puu.sh/wrdYs/42d23f7c36.png)

Trying to replace 'qwe' by nbsp; doesn't work, it just displays nbsp; in chat.

**Comment by nwhitmont** [comment]
@hofman-p You are commenting on a closed issue.  If you have a question or problem, please open a new issue.  Also, for reference, please don't double post to bot GitHub and Stack Overflow, as we monitor bot forums concurrently. Thanks

Duplicate of: https://stackoverflow.com/questions/44700290/cant-add-line-break-when-sending-messages-on-facebook-channel/44769608#44769608
